### ISSUE TITLE
Issues noted at version 0.6.1

### ISSUE THREAD

**Issue by C-Westin** [funtastix/rinnaitouch#19]
@funtastix if you need more information please let me know.

My setup.
- I have a single NC6 controller with Heater and Cooler across 2 zones (A & B)

First off, request for improvement.

1) I'll really need two sensors one for each zone. As the zones are upstairs and downstairs it doesn't make any sense for me to use a single temperature sensor as input
2) the name of the device should just have been Rinnai Touch Test instead of Rinnai Touch Test Zone B. 
![image](https://user-images.githubusercontent.com/51877673/157207398-a249e5f4-3c09-4b2c-9cc9-414091260281.png)

Really that's as far as I get. Most of sensors are unavailable and this also the case for the the three climate thermostats.
![image](https://user-images.githubusercontent.com/51877673/157210082-0233d1b6-d06e-42bb-9dd9-8a73ece199ae.png)

I added a debug level to the log and captured the attached log. Ignore the MQTT climate (and other random entries), That's [Mantorok](https://community.home-assistant.io/u/Mantorok) version of the hvac integration using homebridge. Before I ran this test, I deactivated my homebridge instance and reset the rinnai touch before restarting HA core. 

[log.txt](https://github.com/funtastix/rinnaitouch/files/8204671/log.txt)

**Comment by funtastix** [comment]
Thanks @C-Westin . This was some straight-forward bugs to do with cooling info parsing, mostly a typo when parsing the main OP state (looking for a heater instead of a cooler). Can you test if my change in develop fixes it? Your devices should become available then.

To clarify your suggestion: you'd want to add a temperature sensor for each zone? I assume in addition to the option to add the main one?

**Comment by C-Westin** [comment]
Nice update... 
Its mostly working. Let me come back to you later tonight (hopefully) with some additional issues/change requests

**Comment by funtastix** [comment]
Thanks. Will wait for more feedback. I've fixed a few more issues, and also fixed the naming of the device.

**Comment by funtastix** [comment]
Finally added the fan control, and also managed to resolve the connectivity issues. In the same process I made the whole thing much more responsive, too.

**Comment by C-Westin** [comment]
I've been testing the integration more today on version 0.7.0. I'm loving the integration.

I've seen two things that aren't visible in the log:

1. When I turn the to cooling, I loose my two zones. Zones A & B become unavailable. Then when I turn on the heater, they come back.
2. One 1 instance, the fan ran without any heat / cool active. The integration said the unit was off. At the NC6 controller I could see the fan running. I don't actually believe my unit supports fan speed only fan on/off. Maybe I'll play more with the integration looking at the fan part more....

Overall I find the touch device quite problematic. If you send too many commands its seems to get a bit confused and does weird things.

The device is now being correctly named. Thanks

Following up on my request for multiple temp sensor input....

- I have two zones, upstairs and downstairs.
- I can only add 1 current temperature sensor as input. This temperature essentially is for the whole house. This is how the standard system works and is extremely frustrating.  The standard sensor is downstairs, but upstairs often get extremely hot while downstairs is much cooler. So I want to know the difference between the upstairs and downstairs temperature so I can turn the air on automatically upstairs,
- So I'd like to specify a main temperature sensor for input (maybe I'll average upstairs and downstairs), while additionally being able to include a zone specific current temperature. All this would be is add a temperature to the middle of each zones thermostat card.
![image](https://user-images.githubusercontent.com/51877673/157823814-e3c688a2-8a77-4893-8f87-8762437e9405.png)

I hope that's clear.

**Comment by C-Westin** [comment]
I noted sometime when I restart HA, the external temperature sensor hasn't yet received a value a therefor reports 'unknown' to the rinnai integration causing it to fail. I guess you'll need to capture this and set the value to zero or similar.

log extract:


2022-03-11 21:25:54 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "FRI", "TM": "20:38", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"HGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "F", "CF": "N", "FL": "15", "SN": "Y" }, "GSS": {"HC": "N", "FS": "N", "GV": "N", "PH": "N" }, "APS": {"AV": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "N", "MT": "999" }, "ZBS": {"AE": "N", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-11 21:25:54 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.heater] Heater is OFF
2022-03-11 21:25:54 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in HEAT mode
2022-03-11 21:25:54 INFO (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch entity 192.168.1.180
2022-03-11 21:25:54 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-11 21:25:54 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: unknown
2022-03-11 21:25:54 ERROR (MainThread) [homeassistant.components.climate] Error while setting up rinnaitouch platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/rinnaitouch/climate.py", line 65, in async_setup_entry
async_add_entities([RinnaiTouch(hass, ip_address, name, temperature_entity)])
File "/config/custom_components/rinnaitouch/climate.py", line 90, in __init__
self.update_external_temperature()
File "/config/custom_components/rinnaitouch/climate.py", line 413, in update_external_temperature
self._sensor_temperature = int(round(float(temperature_entity.state)))
ValueError: could not convert string to float: 'unknown'

**Comment by funtastix** [comment]
For those 2 issues described above (zones lost and fan only mode), could you post the logs with the JSON that describes those states, i.e. when the fan is active, then when the zones exists, then when they don't?

I've added temp sensor fields for all zones now, they should be optional.

I should also have fixed the ValueError.

all on develop to test.

**Comment by funtastix** [comment]
For issue #1 (cooling has no zones) I've just pushed 0.7.2 to fix it. Copy and paste is helpful, but it can do things to you... It was putting the cooling zones into the heater :(

**Comment by funtastix** [comment]
I had to remove the temp sensors for zones again. something isn't playing nice, even though I copies and pasted the code basically. I think it'll be a tricky one, because it seems it has to do with using the HA object in different threads...

**Comment by funtastix** [comment]
I've just fixed a problem with zone temp sensors. They are now available on develop. On master, I've released 0.8.0 based on a PyPi library and refactored code (which is also on develop).

**Comment by C-Westin** [comment]
I've had this error a couple of times. Not sure what's causing it

![image](https://user-images.githubusercontent.com/51877673/158056171-cca3da61-515e-4683-bd87-5ce8341921a3.png)



022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "SUN", "TM": "21:00", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "N", "CF": "N", "FL": "16", "SN": "Y" }, "GSO": {"OP": "M", "SP": "18", "AO": "N" }, "GSS": {"CC": "Y", "FS": "Y", "CP": "Y", "AT": "W", "AZ": "W" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "N" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "Y", "MT": "999" }, "ZBS": {"AE": "Y", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling is ON
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Fan Speed is: 16
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling OpMode is: M
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling set temp is: 18
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in COOL mode
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-13 21:48:11 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 27.01
2022-03-13 21:48:12 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] sending empty command
2022-03-13 21:48:12 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] sent empty command
2022-03-13 21:48:12 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=84, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 51748), raddr=('192.168.1.180', 27847)> / False
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "SUN", "TM": "21:00", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "N", "CF": "N", "FL": "16", "SN": "Y" }, "GSO": {"OP": "M", "SP": "18", "AO": "N" }, "GSS": {"CC": "Y", "FS": "Y", "CP": "Y", "AT": "W", "AZ": "W" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "N" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "Y", "MT": "999" }, "ZBS": {"AE": "Y", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling is ON
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Fan Speed is: 16
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling OpMode is: M
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling set temp is: 18
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in COOL mode
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-13 21:48:16 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 27.01
2022-03-13 21:48:17 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=84, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 51748), raddr=('192.168.1.180', 27847)> / False
2022-03-13 21:48:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139760438554432] Option not valid for Rinnai Touch Preset Select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 53, in async_select_option
raise ValueError(f"Option {option} not valid for {entity.name}")
ValueError: Option not valid for Rinnai Touch Preset Select
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "SUN", "TM": "21:00", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "N", "CF": "N", "FL": "16", "SN": "Y" }, "GSO": {"OP": "M", "SP": "18", "AO": "N" }, "GSS": {"CC": "Y", "FS": "Y", "CP": "Y", "AT": "W", "AZ": "W" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "N" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "Y", "MT": "999" }, "ZBS": {"AE": "Y", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling is ON
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Fan Speed is: 16
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling OpMode is: M
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling set temp is: 18
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in COOL mode
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-13 21:48:21 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 27.01
2022-03-13 21:48:22 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=84, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 51748), raddr=('192.168.1.180', 27847)> / False
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "SUN", "TM": "21:00", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "N", "CF": "N", "FL": "16", "SN": "Y" }, "GSO": {"OP": "M", "SP": "18", "AO": "N" }, "GSS": {"CC": "Y", "FS": "Y", "CP": "Y", "AT": "W", "AZ": "W" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "N" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "Y", "MT": "999" }, "ZBS": {"AE": "Y", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling is ON
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Fan Speed is: 16
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling OpMode is: M
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling set temp is: 18
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in COOL mode
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-13 21:48:26 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 27.01
2022-03-13 21:48:27 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=84, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 51748), raddr=('192.168.1.180', 27847)> / False
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "SUN", "TM": "21:01", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "N", "CF": "N", "FL": "16", "SN": "Y" }, "GSO": {"OP": "M", "SP": "18", "AO": "N" }, "GSS": {"CC": "Y", "FS": "Y", "CP": "Y", "AT": "W", "AZ": "W" }, "APS": {"AV": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "N" }, "ZCO": {"UE": "N" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "999" }, "ZAS": {"AE": "Y", "MT": "999" }, "ZBS": {"AE": "Y", "MT": "999" }, "ZCS": {"AE": "N", "MT": "999" }, "ZDS": {"AE": "N", "MT": "999" } } }]
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling is ON
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Fan Speed is: 16
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling OpMode is: M
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.cooler] Cooling set temp is: 18
2022-03-13 21:48:31 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] We are in COOL mode
2022-03-13 21:48:32 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.upstairs_temperature
2022-03-13 21:48:32 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 27.01
2022-03-13 21:48:32 DEBUG (MainThread) [custom_components.rinnaitouch.pyrinnaitouch.system] Client Variable: <socket.socket fd=84, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 51748), raddr=('192.168.1.180', 27847)> / False

**Comment by funtastix** [comment]
I cannot find an obvious fault. Any steps that you are taking to reproduce this? What is your select entity showing as options? Should be cooling and heater?

What happens when you turn the unit off? I'd love to see a log of the JSON of that. Maybe you're not in any mode at that point and I'd have to safeguard for that.

**Comment by funtastix** [comment]
Also, looking that this is traced to websocket API, this must originate on the UI. Either it's during rendering the select or during interaction.

**Comment by C-Westin** [comment]
Hi @funtastix, since upgrading to 0.9.0 and also 0.9.1 via HACS i'm getting the following issue on restart.

The unit itself is off but it cooling mode.

2022-03-15 00:08:28 DEBUG (MainThread) [pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "N", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "MON", "TM": "00:00", "BP": "Y", "RG": "N", "ST": "C", "MD": "N", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" }, "STM": {"DY": "MON", "TM": "00:00", "SV": "N" } } }]
2022-03-15 00:08:28 ERROR (MainThread) [pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (IndexError('list index out of range'))
2022-03-15 00:08:28 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.average_temperature
2022-03-15 00:08:28 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 25.2
2022-03-15 00:08:30 DEBUG (MainThread) [pyrinnaitouch.system] sending empty command
2022-03-15 00:08:30 DEBUG (MainThread) [pyrinnaitouch.system] sent empty command
2022-03-15 00:08:30 DEBUG (MainThread) [pyrinnaitouch.system] Client Variable: <socket.socket fd=45, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 52504), raddr=('192.168.1.180', 27847)> / False
2022-03-15 00:08:33 DEBUG (MainThread) [pyrinnaitouch.system] Sequence: 1 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": " ", "ZB": " ", "ZC": " ", "ZD": " " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "MON", "TM": "23:21", "BP": "Y", "RG": "N", "ST": "N", "MD": "N", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } }]
2022-03-15 00:08:33 ERROR (MainThread) [pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (IndexError('list index out of range'))
2022-03-15 00:08:33 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.average_temperature
2022-03-15 00:08:33 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 25.2
2022-03-15 00:08:35 DEBUG (MainThread) [pyrinnaitouch.system] Creating new client...
2022-03-15 00:08:35 DEBUG (MainThread) [pyrinnaitouch.system] Client Variable: <socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.30', 52528), raddr=('192.168.1.180', 27847)> / False
2022-03-15 00:08:36 ERROR (MainThread) [pyrinnaitouch.system] Couldn't decode JSON (exception), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2022-03-15 00:08:36 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.average_temperature
2022-03-15 00:08:36 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 25.2
2022-03-15 00:08:40 DEBUG (MainThread) [pyrinnaitouch.system] Error 1st phase during renewConnection [Errno 107] Socket not connected
2022-03-15 00:08:40 DEBUG (MainThread) [pyrinnaitouch.system] Creating new client...
2022-03-15 00:08:40 DEBUG (MainThread) [pyrinnaitouch.system] Error during renewConnection [Errno 111] Connection refused
2022-03-15 00:08:40 DEBUG (MainThread) [pyrinnaitouch.system] renewing connection failed, not sending command
2022-03-15 00:08:40 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor entity name: sensor.average_temperature
2022-03-15 00:08:40 DEBUG (MainThread) [custom_components.rinnaitouch.climate] External temperature sensor reports: 25.2

**Comment by funtastix** [comment]
Your cooling mode is behaving quite interestingly. I don't understand your latest logs. They basically say you don't have a heater or cooler installed, and the cooling part is missing. That doesn't seem like normal behaviour.

It doesn't seem to be a network error as the JSON response is well formed

**Comment by C-Westin** [comment]
My unit is misbehaving. I re-added it to my wifi and it's still sending odd messages. Though the standard touch app can communicate with device no problem.

**Comment by funtastix** [comment]
Did you power cycle it?

The Rinnai app, is it using local or cloud? I assume it has a cloud symbol in the lower right corner?

**Comment by C-Westin** [comment]
> Did you power cycle it?
> 
> The Rinnai app, is it using local or cloud? I assume it has a cloud symbol in the lower right corner?

Many times power cycling. It doesn't seem to change the odd messaging. 

I am using cloud integration and I couldn't find any documentation on how to turn it back to local only. That's why I re-addrd it to the wifi. I was hoping it would ask me during the onboarding process.

**Comment by funtastix** [comment]
You'll have to make sure to disconnect all clients from the unit. Reboot it (power down and back up) while doing a reset using the button on the unit for 5 seconds I think. Make sure nothing tries to connect to it l, then use the app to set it up from scratch. It should be flashing orange AFAIK to signal it's back in access point mode.

**Comment by C-Westin** [comment]
I'm going to close this. The issues that I've logged previously have been addressed.
I do have an problem with cooling that I'm yet to get to the bottom of. I'll log a new issue once I have time to debug further

**Comment by funtastix** [comment]
Great. Let me known if you want me to have a look. I can now emulate any JSON output and debug other systems that way
