### ISSUE TITLE
Can't change HVAC mode or preset after update

### ISSUE THREAD

**Issue by nathbullen** [funtastix/rinnaitouch#57]
First of all, thanks mate for putting in the work to try to fix the slowdown issue 🙏

Unfortunately since updating to 0.11.1, I can't change my HVAC mode or preset mode from what is set on the networker. If the networker is set to evap, then changing the selector in HA to heat just bounces back to 'cool' after a second. Preset modes behave the same unfortunately - can't change between manual and auto modes. 

Other than that, everything is super responsive, thank you!

I see this in the logs:

`Logger: pyrinnaitouch.system
Source: /usr/local/lib/python3.10/site-packages/pyrinnaitouch/system.py:223
First occurred: 7:53:08 AM (37 occurrences)
Last logged: 8:10:18 AM

Fired off command: (N000001{{"ECOM": {{"GSO": {{"OP": "M" }} }} }})
Fired off command: (N000001{"HGOM": {"OOP": {"ST": "N" } } })
Fired off command: (N000001{{"HGOM": {{"GSO": {{"OP": "M" }} }} }})
Fired off command: (N000002{"HGOM": {"OOP": {"ST": "N" } } })
Fired off command: (N000002{{"HGOM": {{"GSO": {{"OP": "M" }} }} }})`

`Logger: pyrinnaitouch.system
Source: /usr/local/lib/python3.10/site-packages/pyrinnaitouch/system.py:412
First occurred: 7:56:40 AM (5 occurrences)
Last logged: 7:57:11 AM

Couldn't decode JSON (exception), skipping (IndexError('list index out of range'))`

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/rinnaitouch/climate.py:335
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 7:56:20 AM (1 occurrences)
Last logged: 7:56:20 AM

[139624213098080] 'RinnaiSystem' object has no attribute 'set_heater_fan_speed'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 681, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 721, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/rinnaitouch/climate.py", line 317, in async_set_temperature
    await self.async_set_target_temperature(kwargs.get(ATTR_TEMPERATURE))
  File "/config/custom_components/rinnaitouch/climate.py", line 335, in async_set_target_temperature
    await self._system.set_heater_fan_speed(target_temperature)
AttributeError: 'RinnaiSystem' object has no attribute 'set_heater_fan_speed'`

**Comment by funtastix** [comment]
Can you try with 0.11.2 (https://github.com/funtastix/rinnaitouch/releases/tag/0.11.2)

**Comment by nathbullen** [comment]
Amazing mate, thanks for fixing that so fast, seems to be all good now 🙏
Response time seems equally fast and no longer slowing my whole instance down randomly. Thanks!!
